### ISSUE TITLE
Expired link

### ISSUE THREAD

**Issue by javad-rahmannezhad** [yousefvand/pronunciations#2]
Hi,

I hope you're doing awesome! The Mediafire link for the package seems to have taken a nap and isn't working anymore. 😬

Any chance you could wake it up or drop a fresh link? 

Thanks a bunch!

Cheers,

Javad

**Comment by yousefvand** [comment]
Hey Javad
I don't have access to any server at the moment. For myself I used chrome with GitZip extension.
